name: Upload

on: [release]

jobs:
  build:
    name: upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test and Vet
        run: |
          go test -v ./...
          go vet -v ./...

      - name: Compile
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o drinit-amd64 cmd/drinit/drinit.go
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o drinitctl-amd64 cmd/drinitctl/drinitctl.go

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: drinit-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: drinitctl-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
